In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
data_dir = '1990_quarterly/1990.q1-q4.by_area/'

In [4]:
! ls $data_dir | head -10

1990.q1-q4 01000 Alabama -- Statewide.csv
1990.q1-q4 01001 Autauga County, Alabama.csv
1990.q1-q4 01003 Baldwin County, Alabama.csv
1990.q1-q4 01005 Barbour County, Alabama.csv
1990.q1-q4 01007 Bibb County, Alabama.csv
1990.q1-q4 01009 Blount County, Alabama.csv
1990.q1-q4 01011 Bullock County, Alabama.csv
1990.q1-q4 01013 Butler County, Alabama.csv
1990.q1-q4 01015 Calhoun County, Alabama.csv
1990.q1-q4 01017 Chambers County, Alabama.csv
ls: write error: Broken pipe

In [5]:
Alabama_file = pd.read_csv(data_dir+'1990.q1-q4 01000 Alabama -- Statewide.csv')

In [6]:
Alabama_file.head()

,area_fips,own_code,industry_code,agglvl_code,size_code,year,qtr,disclosure_code,area_title,own_title,...,oty_month3_emplvl_chg,oty_month3_emplvl_pct,oty_total_qtrly_wages_chg,oty_total_qtrly_wages_pct,oty_taxable_qtrly_wages_chg,oty_taxable_qtrly_wages_chg.1,oty_qtrly_contributions_chg,oty_qtrly_contributions_pct,oty_avg_wkly_wage_chg,oty_avg_wkly_wage_pct
0,1000,0,10,50,0,1990,1,NaN,Alabama -- Statewide,Total Covered,...,28775,1.9,503840949,6.9,-4742937405,-100.0,-65031838,-100.0,17,4.7
1,1000,0,10,50,0,1990,2,NaN,Alabama -- Statewide,Total Covered,...,42548,2.7,494336997,6.5,-2622393690,-100.0,-38453454,-100.0,15,4.0
2,1000,0,10,50,0,1990,3,NaN,Alabama -- Statewide,Total Covered,...,26369,1.7,494308585,6.5,-1506419025,-100.0,-23031527,-100.0,16,4.3
3,1000,0,10,50,0,1990,4,NaN,Alabama -- Statewide,Total Covered,...,24414,1.5,575104731,7.1,-1110776070,-100.0,-17384452,-100.0,22,5.6
4,1000,1,10,51,0,1990,1,NaN,Alabama -- Statewide,Federal Government,...,2362,3.7,44684316,10.1,0,0.0,0,0.0,41,7.7

In [7]:
Alabama_Autaga_file = pd.read_csv(data_dir+'1990.q1-q4 01001 Autauga County, Alabama.csv')

In [8]:
Alabama_Autaga_file.head()

,area_fips,own_code,industry_code,agglvl_code,size_code,year,qtr,disclosure_code,area_title,own_title,...,oty_month3_emplvl_chg,oty_month3_emplvl_pct,oty_total_qtrly_wages_chg,oty_total_qtrly_wages_pct,oty_taxable_qtrly_wages_chg,oty_taxable_qtrly_wages_chg.1,oty_qtrly_contributions_chg,oty_qtrly_contributions_pct,oty_avg_wkly_wage_chg,oty_avg_wkly_wage_pct
0,1001,0,10,70,0,1990,1,NaN,"Autauga County, Alabama",Total Covered,...,-59,-0.8,1412456,4.0,-23847194,-100.0,-223343,-100.0,12,3.4
1,1001,0,10,70,0,1990,2,NaN,"Autauga County, Alabama",Total Covered,...,-103,-1.3,501910,1.4,-13228402,-100.0,-157184,-100.0,7,2.1
2,1001,0,10,70,0,1990,3,NaN,"Autauga County, Alabama",Total Covered,...,170,2.2,1133202,3.3,-8104488,-100.0,-109830,-100.0,5,1.5
3,1001,0,10,70,0,1990,4,NaN,"Autauga County, Alabama",Total Covered,...,71,0.9,2317021,6.5,-5592723,-100.0,-79441,-100.0,16,4.6
4,1001,1,10,71,0,1990,1,NaN,"Autauga County, Alabama",Federal Government,...,12,16.7,99448,25.5,0,0.0,0,0.0,65,15.6

In [9]:
Alabama_Autaga_file.loc[0][20]

360

In [10]:
Alabama_file.columns

Index(['area_fips', 'own_code', 'industry_code', 'agglvl_code', 'size_code',
       'year', 'qtr', 'disclosure_code', 'area_title', 'own_title',
       'industry_title', 'agglvl_title', 'size_title', 'qtrly_estabs_count',
       'month1_emplvl', 'month2_emplvl', 'month3_emplvl', 'total_qtrly_wages',
       'taxable_qtrly_wages', 'qtrly_contributions', 'avg_wkly_wage',
       'lq_disclosure_code', 'lq_qtrly_estabs_count', 'lq_month1_emplvl',
       'lq_month2_emplvl', 'lq_month3_emplvl', 'lq_total_qtrly_wages',
       'lq_taxable_qtrly_wages', 'lq_qtrly_contributions', 'lq_avg_wkly_wage',
       'oty_disclosure_code', 'oty_qtrly_estabs_count_chg',
       'oty_qtrly_estabs_count_pct_chg', 'oty_month1_emplvl_chg',
       'oty_month1_emplvl_pct', 'oty_month2_emplvl_chg',
       'oty_month2_emplvl_pct', 'oty_month3_emplvl_chg',
       'oty_month3_emplvl_pct', 'oty_total_qtrly_wages_chg',
       'oty_total_qtrly_wages_pct', 'oty_taxable_qtrly_wages_chg',
       'oty_taxable_qtrly_wages_chg.1', 'oty_qtrly_contributions_chg',
       'oty_qtrly_contributions_pct', 'oty_avg_wkly_wage_chg',
       'oty_avg_wkly_wage_pct'],
      dtype='object')

In [11]:
Alabama_file.loc[100]['industry_title']

'Supermarkets and other grocery stores'

In [12]:
Alabama_file['industry_code']

0           10
1           10
2           10
3           10
4           10
         ...
7519    814110
7520        10
7521        10
7522        10
7523        10
Name: industry_code, Length: 7524, dtype: object

In [ ]:
plt.plot(list(Alabama_file['industry_code']))
plt.show()